### ISSUE TITLE
Supply additional information on activities. 

### ISSUE THREAD

**Issue by wolfiex** [WCRP-CMIP/CMIP6Plus_CVs#17]
I am wondering if we should provide and active page URL or paper reference for each activity. 

E.g. 
```
        "CORDEX"  :   {
                               "long_name":  "Coordinated Regional Climate Downscaling Experiment",
                               "URL": "https://www.wcrp-climate.org/modelling-wgcm-mip-catalogue/cmip6-endorsed-mips-article/1052-modelling-cmip6-cordex"
                          }

**Comment by taylor13** [comment]
Good idea.  Seems to me that would be useful.

**Comment by durack1** [comment]
agreed, not all projects have webpages, but many do so if you can find it, add it in

**Comment by wolfiex** [comment]
I feel that if we are planning on including an activity, there should at-least be a page on github / CMIPIPO / WCRP? describing their aim, purpose , funding etc. 

It could be a requirement that the application to add a new activity requires a short description form (used to create this) for such an activity?

**Comment by durack1** [comment]
@wolfiex I agree, but there is always the fringe case of an example that doesn't follow that thinking. We'd also thought about including a URL to an institution, which admittedly is more or less solved using the RORs, but that was also a challenge, with many not having a persistent URL that identifies the institution (purpose, funding, who, etc). In the case that we REQUIRE a MIP to register (ala https://wcrp-cmip.org/launch-of-mip-registration/) then this can be used directly, and it's also CMIP-IPO managed info, which makes it even simpler
