### ISSUE TITLE
Technical: add version badge

### ISSUE THREAD

**Issue by durack1** [WCRP-CMIP/CMIP6Plus_CVs#26]
Having the version badge on the homepage made for a very useful quick check - see https://github.com/WCRP-CMIP/CMIP6_CVs/

![Screenshot 2023-11-21 at 6 10 28 AM](https://github.com/WCRP-CMIP/CMIP6Plus_CVs/assets/3229632/e6952358-3f1c-474f-bc9a-2450452bceaa)

Adding the same to this repo would be very useful

**Comment by wolfiex** [comment]
<img width="949" alt="Screenshot 2023-11-23 at 04 06 09" src="https://github.com/WCRP-CMIP/CMIP6Plus_CVs/assets/15582577/2dfdde1a-eb96-485d-b43d-b7ebe6c2c071">
