### ISSUE TITLE
source_id: request to add MIROC6

### ISSUE THREAD

**Issue by hshiogama** [WCRP-CMIP/CMIP6Plus_CVs#35]
Please use the same CV of MIROC6 for CMIP6 and add LESFMIP the activity list.

**Comment by wolfiex** [comment]
Hi @hshiogama , 

I am prototyping the first instance of automations in relation to adding a new SourceID.
Would you kindly fill out the required form (as is outlined in the wiki)

https://github.com/WCRP-CMIP/CMIP6Plus_CVs/wiki/Adding-a-new-Source_ID

and report any problems / feedback you face, here.

This will automatically generate a pull request with your changes as is seen by: https://github.com/WCRP-CMIP/CMIP6Plus_CVs/pull/38

Kind regards,
Daniel
