### ISSUE TITLE
Adding NASA GISS Institution / Models to CMIP6Plus

### ISSUE THREAD

**Issue by ajoherron** [WCRP-CMIP/CMIP6Plus_CVs#60]
institution_id = NASA-GISS
institution = NASA Goddard Institute for Space Studies, New York, NY 10025, USA

Models (same as CMIP6):
GISS-E2-1-G
GISS-E2-1-G-CC
GISS-E2-1-H
GISS-E2-2-G
GISS-E2-2-H
GISS-E3-G

**Comment by wolfiex** [comment]
Hi Alex, 

Can I check which models, activity id and MIP you will be contributing to?

Institution ROR: https://ror.org/01cyfxe35

Thanks, 
Daniel

**Comment by ajoherron** [comment]
Hi Daniel,

Sure thing - here are the models, activity IDs, and MIPs that we'll be contributing to:

Models:
GISS-E2-1-G
GISS-E2-1-G-CC
GISS-E2-1-H
GISS-E2-2-G
GISS-E2-2-H
GISS-E3-G

Activity ID: DAMIP

MIP: LESFMIP

Please let me know if there's any additional information I can provide that would be helpful.

Best,
Alex

**Comment by ajoherron** [comment]
Understood. In that case, let's just stick with GISS-E2-1-G (Activity ID: DAMIP, MIP: LESFMIP) for now.

Thanks for all your help.

**Comment by matthew-mizielinski** [comment]
@wolfiex, can you check the process -- the GISS model has not made it into the CMIP6Plus_CV.json, but there is another file alongside it with the change.

**Comment by wolfiex** [comment]
The create script did not trigger for some reason. Pushed through with the latest updates.
