### ISSUE TITLE
TIPMIP: Experiments requested by TIPMIP

### ISSUE THREAD

**Issue by matthew-mizielinski** [WCRP-CMIP/CMIP6Plus_CVs#78]
# General Issue: New experiments

TIPMIP have asked to add experiments to CMIP6Plus and their experiment definition appears to include the following set of experiments;

See [here](https://tipmip.pik-potsdam.de/news/tipmip_esm_protocol/) for diagramatic description of the experiments: 

experiment id | activity id | experiment | tier | sub experiment id | parent experiment id | required model components | additional allowed model components | start year | end year | min number of years | parent activity id | description
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
esm-up2p0 | TIPMIP | ramp up at X Gt C/yr to Global Warming Level of 2K at 0.2 K/decade | 1 | none | esm-piControl | AOGCM BGC | AER CHEM |   |   | 100 | CMIP |  
esm-up2p0-swl2p0 | TIPMIP | zero emissions at global warming level of 2K | 1 | none | esm-up2p0 | AOGCM BGC | AER CHEM |   |   | 50 | TIPMIP |  
esm-up2p0-swl2p0-50y-dn2p0 | TIPMIP | ramp down from global warming level of 2K at 0.2 K/decade | 1 | none | esm-up2p0-swl2p0 | AOGCM BGC | AER CHEM |   |   | 100 | TIPMIP |  
esm-up2p0-swl4p0 | TIPMIP | zero emissions at global warming level of 4K | 1 | none | esm-up2p0 | AOGCM BGC | AER CHEM |   |   | 50 | TIPMIP |  
esm-up2p0-swl4p0-50y-dn2p0 | TIPMIP | ramp down from global warming level of 2K at 0.2 K/decade | 1 | none | esm-up2p0-swl4p0 | AOGCM BGC | AER CHEM |   |   | 100 | TIPMIP |  
esm-up2p0-swl4p0-50y-dn2p0-swl2p0 | TIPMIP | zero emissions at global warming level of 2K after ramp down from global   warming of 4K | 1 | none | esm-up2p0-swl4p0-50y-dn2p0 | AOGCM BGC | AER CHEM |   |   | 50 | TIPMIP |  

The experiment names are systematic, but do get a little long (33 characters max). I don't think this will cause any problems in CMOR, but we might need to confirm that the ESGF interfaces can handle this.

As far as suitability for CMIP6Plus goes, I think the match up with CMIP7's goals is sufficient.

@durack1 could you review the information above?

**Comment by durack1** [comment]
the metagrid ESGF interface maxes out at ~12 chars before ellipses creep in, not an issue for uniquely identifying info, but does  mean that it will be harder to identify the esm-up2p0-swl2p0-5.. or longer experiment_id's. Presumably the esm-piControl is the CMIP6 experiment_id?

Below is the listing of source_id's that published esm-piControl sims to CMIP6:

```python
ACCESS-ESM1-5 (860)
AWI-ESM-1-REcoM (313)
BCC-CSM2-MR (508)
CESM2 (2226)
CNRM-ESM2-1 (1548)
CanESM5 (1010)
CanESM5-CanOE (660)
EC-Earth3-CC (705)
GFDL-ESM4 (966)
GISS-E2-1-G-CC (573)
MIROC-ES2L (904)
MPI-ESM1-2-LR (1281)
MRI-ESM2-0 (1090)
NorESM2-LM (933)
UKESM1-0-LL (1172)
```

**Comment by matthew-mizielinski** [comment]
> Presumably the esm-piControl is the CMIP6 experiment_id?

Correct -- this is already in the CMIP6Plus CVs as part of the DECK.  Groups may use that as the parent or submit a new one (expecting UKESM1-1-LL esm-piControl will need to be included).

Regarding the length of the experiment id in the search index. This is an extreme case of something we already have (some of the DCPP experiments have long names too).  Personal opinion is that as long as the experiment proposers are aware of the issue then this isn't a problem. We could request that the metagrid devs make that side bar expandable and (ideally) allow the contents of the selection boxes to adapt.

**Comment by durack1** [comment]
> > Presumably the esm-piControl is the CMIP6 experiment_id?
> 
> Correct -- this is already in the CMIP6Plus CVs as part of the DECK.

All looks good to me, is there any point in adding parent_experiment_id `CMIP6:esm-piControl` (we can't validate this within the repo, as this is using a standing prior-phase initialization) or is this starting to get into a tangle that we don't want to complicate ourselves with?

**Comment by matthew-mizielinski** [comment]
> > > Presumably the esm-piControl is the CMIP6 experiment_id?
> > 
> > 
> > Correct -- this is already in the CMIP6Plus CVs as part of the DECK.
> 
> All looks good to me, is there any point in adding parent_experiment_id `CMIP6:esm-piControl` (we can't validate this within the repo, as this is using a standing prior-phase initialization) or is this starting to get into a tangle that we don't want to complicate ourselves with?

`esm-piControl` could well be submitted to CMIP6Plus rather than CMIP6 depending on the model. I don't think we should worry too much about this and leave it to project documentation.

**Comment by matthew-mizielinski** [comment]
@sciconaut, does the experiment list above look correct

**Comment by klauswyser** [comment]
Thanks for preparing the experiment descriptions and sorry for the belated reply. I have a couple of comments to table entries in the description, how do I do this in the most efficient way? Copy the table to an issue and update? Or is there a file with the table  where I could suggest changes and add comments?

**Comment by klauswyser** [comment]
And another question: this list of experiments isn't complete, we already plan for tier 2 simulations with swl1.5 or swl3.0, different lengths of overshoot, faster or slower ramp-downs, etc. I assume it won't be a problem to add more experiments later as long as we don't modify any existing experiment, or?

**Comment by taylor13** [comment]
Note that one constraint on experiment names (as they appear in the CMIP data base and in file names) is that a period (i.e., ".") is not permitted.  This is because in file names the "." is reserved to separate the the file type suffix (e.g., ".nc") from the filename. So if you want a name like "swl1.5", it will have to be modified for use in the CMIP database.  In CMIP6, for example, the identification of an experiment consistent with "SSP5-8.5" scenario were referenced as "ssp585" in CMIP.   And an experiment with CO2 halved abruptly was referenced as "abrupt-0p5xCO2" (where "p" stands for "point").

Some options you might consider in place of "swl1.5" include: "swl15", "swl1-5" or "swl1p5".

Happy to iterate.

**Comment by klauswyser** [comment]
Thanks, I'm aware of this restriction and just sloppily wrote gwl1.5 in the text. Matt's table in the description already takes this into account and replaces "." by "p", we will continue with that.

**Comment by taylor13** [comment]
Excellent!  I obviously haven't been keeping up.

**Comment by matthew-mizielinski** [comment]
Hi @klauswyser,

Feel free to copy the table and update it, but if you do please highlight the changes. When it comes to extending with new experiments later I don't see a problem as long as the naming is consistent and you don't conflict with other experiments.

**Comment by klauswyser** [comment]
Thanks a lot for the draft of the experiment metadata for the CMIP6plus tables. Here are some suggested modifications, based on the information in [ESM experiment protocol for TIPMIP](https://docs.google.com/document/d/17pU1pHv6EyBWCVfV1p4lgxv7AkpUxRvp/edit?usp=sharing&ouid=100924845281827758907&rtpof=true&sd=true). This information will also be included in the TIPMIP experiment protocol paper that currently is in the writing.


| experiment id | activity id | experiment | tier | sub experiment id | parent experiment id | required model components | additional allowed model components | start year | end year | min number of years | parent activity id | description
|-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
| esm-up2p0 | TIPMIP | ramp up with *~X Gt C/yr to Global Warming Level of 2K at  0.2 K/decade~ constant CO2 emissions that yield a warming of approximately 2 K/century (see TIPMIP experiment protocol for details)*  | 1 | none | esm-piControl | AOGCM BGC | AER CHEM |   |   | *~100~ 215* | CMIP |  
| esm-up2p0-swl2p0 | TIPMIP | zero *CO2* emissions *~at global warming level of 2K~, branching off from esm-up2p0 the year after it passes the 2 K global warming level* | 1 | none | esm-up2p0 | AOGCM BGC | AER CHEM |   |   | *~50~ 300* | TIPMIP |  
| esm-up2p0-swl2p0-50y-dn2p0 | TIPMIP | ramp down from global warming level of 2K *~at 0.2 K/decade~ after 50 years, with CO2 emissions that are the negative of those used in esm-up2p0* | 1 | none | esm-up2p0-swl2p0 | AOGCM BGC | AER CHEM |   |   | 100 | TIPMIP |  
| esm-up2p0-swl4p0 | TIPMIP | zero *CO2* emissions *~at global warming level of 4K~, branching off  from esm-up2p0 the year after it passes the 4 K global warming level* | 1 | none | esm-up2p0 | AOGCM BGC | AER CHEM |   |   | *~50~300* | TIPMIP |  
| esm-up2p0-swl4p0-50y-dn2p0 | TIPMIP | ramp down from global warming level of *~2~ 4* K *~at 0.2 K/decade~ after 50 years, with CO2 emissions that are the negative of those used in esm-up2p0* | 1 | none | esm-up2p0-swl4p0 | AOGCM BGC | AER CHEM |   |   | *~100~200* | TIPMIP |  
| esm-up2p0-swl4p0-50y-dn2p0-swl2p0 | TIPMIP | zero *CO2* emissions *~at global warming level of 2K after~,  branching off from esm-up2p0-swl4p0-50y-dn2p0 after it passes the 2 K global warming level ~ramp down from global warming of 4K~* | 1 | none | esm-up2p0-swl4p0-50y-dn2p0 | AOGCM BGC | AER CHEM |   |   | *~50~ 300* | TIPMIP |  


### Notes

Line 1: ramp-up goes to GWL4 which means at least 200 yrs. Add 15 yrs to compute the 31-yr running mean. Shorten experiment attribute. Add reference to TIPMIP experiment protocol (unfortunately not published yet)

Lines 2 & 4 & 6: SWL simulations should go for at least 300 yrs. Update experiment attribute to describe more precisely when to launch the GWL experiments

Lines 3 & 5: Update experiment attribute to describe more precisely the ramp-down experiments.

**Comment by klauswyser** [comment]
One open question is still if we should use "swl" or "gwl" in the experiment_id's of the different experiments. The [ESM experiment protocol for TIPMIP](https://docs.google.com/document/d/17pU1pHv6EyBWCVfV1p4lgxv7AkpUxRvp/edit?usp=sharing&ouid=100924845281827758907&rtpof=true&sd=true) uses "gwl",  also in [this overview](https://tipmip.pik-potsdam.de/news/tipmip_esm_protocol/) "gwl" is used.

**Comment by matthew-mizielinski** [comment]
> One open question is still if we should use "swl" or "gwl" in the experiment_id's of the different experiments. The [ESM experiment protocol for TIPMIP](https://docs.google.com/document/d/17pU1pHv6EyBWCVfV1p4lgxv7AkpUxRvp/edit?usp=sharing&ouid=100924845281827758907&rtpof=true&sd=true) uses "gwl", also in [this overview](https://tipmip.pik-potsdam.de/news/tipmip_esm_protocol/) "gwl" is used.

Looks like you are talking yourself into using "gwl", if it is used in papers and websites it would be good to be consistent, plus the phrase "global warming level" is used in the experiment descriptions. I'd recommend updating the table above with this change.

**Comment by jprb-walton** [comment]
> > One open question is still if we should use "swl" or "gwl" in the experiment_id's of the different experiments. The [ESM experiment protocol for TIPMIP](https://docs.google.com/document/d/17pU1pHv6EyBWCVfV1p4lgxv7AkpUxRvp/edit?usp=sharing&ouid=100924845281827758907&rtpof=true&sd=true) uses "gwl", also in [this overview](https://tipmip.pik-potsdam.de/news/tipmip_esm_protocol/) "gwl" is used.
> 
> Looks like you are talking yourself into using "gwl", if it is used in papers and websites it would be good to be consistent, plus the phrase "global warming level" is used in the experiment descriptions. I'd recommend updating the table above with this change.

I'd agree with using "gwl" instead of "swl" (partly because I've forgotten what swl originally stood for, and "everyone" knows about gwl).

**Comment by jprb-walton** [comment]
> Thanks a lot for the draft of the experiment metadata for the CMIP6plus tables. Here are some suggested modifications, based on the information in [ESM experiment protocol for TIPMIP](https://docs.google.com/document/d/17pU1pHv6EyBWCVfV1p4lgxv7AkpUxRvp/edit?usp=sharing&ouid=100924845281827758907&rtpof=true&sd=true). This information will also be included in the TIPMIP experiment protocol paper that currently is in the writing.

These mods look fine to me, Klaus: well done.   Perhaps we could tweak the descriptions slightly to ensure they're consistent, and concise?  The virtue of having a modular naming system _(esm-up2p0, esm-up2p0-gwl2p0,  esm-up2p0-gwl2p0-50y-dn2p0_, etc) is that, for a given experiment, we can refer to preceding steps using their names without having to describe the steps - e.g. _esm-up2p0-gwl4p0-50y-dn2p0-gwl2p0_ = zero CO2 emissions at global warming level of 2K, branching off from _esm-up2p0-gwl4p0-50y-dn2p0_.

**Comment by klauswyser** [comment]
Thanks for the helpful comments, appreciate!

Here is a new attempt, "swl" replaced by "gwl" and experiment descriptions shortened as @jprb-walton suggested. What do you think?

| experiment id | activity id | experiment | tier | sub experiment id | parent experiment id | required model components | additional allowed model components | start year | end year | min number of years | parent activity id | description
|-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
| esm-up2p0 | TIPMIP | ramp up simulation with constant CO2 emissions yielding a warming of approximately 2 K/century (see TIPMIP experiment protocol for details)  | 1 | none | esm-piControl | AOGCM BGC | AER CHEM |   |   | 215 | CMIP |  
| esm-up2p0-gwl2p0 | TIPMIP | zero CO2 emissions simulation starting at global warming level of 2K, branching off from esm-up2p0 | 1 | none | esm-up2p0 | AOGCM BGC | AER CHEM |   |   | 300 | TIPMIP |  
| esm-up2p0-gwl2p0-50y-dn2p0 | TIPMIP | ramp down simulation with CO2 emissions that are the negative of those used in esm-up2p0, branching off from esm-up2p0-gwl2p0 after 50 years | 1 | none | esm-up2p0-gwl2p0 | AOGCM BGC | AER CHEM |   |   | 100 | TIPMIP |  
| esm-up2p0-gwl4p0 | TIPMIP | zero CO2 emissions simulation starting at global warming level of 4K, branching off from esm-up2p0 | 1 | none | esm-up2p0 | AOGCM BGC | AER CHEM |   |   | 300 | TIPMIP |  
| esm-up2p0-gwl4p0-50y-dn2p0 | TIPMIP | ramp down simulation with CO2 emissions that are the negative of those used in esm-up2p0, branching off from esm-up2p0-gwl4p0 after 50 years | 1 | none | esm-up2p0-gwl4p0 | AOGCM BGC | AER CHEM |   |   | 200 | TIPMIP |  
| esm-up2p0-gwl4p0-50y-dn2p0-gwl2p0 | TIPMIP | zero CO2 emissions simulation starting at global warming level of 2K, branching off from esm-up2p0-swl4p0-50y-dn2p0 | 1 | none | esm-up2p0-gwl4p0-50y-dn2p0 | AOGCM BGC | AER CHEM |   |   | 300 | TIPMIP |

**Comment by durack1** [comment]
> One open question is still if we should use "swl" or "gwl" in the experiment_id's of the different experiments. The [ESM experiment protocol for TIPMIP](https://docs.google.com/document/d/17pU1pHv6EyBWCVfV1p4lgxv7AkpUxRvp/edit?usp=sharing&ouid=100924845281827758907&rtpof=true&sd=true) uses "gwl", also in [this overview](https://tipmip.pik-potsdam.de/news/tipmip_esm_protocol/) "gwl" is used.

@klauswyser can you open this google doc up for world-viewable/commentable please? It's locked down at this moment

**Comment by klauswyser** [comment]
Hi @durack1 - the Google doc mentioned above is a milestone report from the TipESM project and as such not public, I'm afraid. Many of those invited to discuss the experiment names here are member of OptimESM, TipESM or TIPMIP and have access to the MS1 report which is why I did mention it here.

**Comment by klauswyser** [comment]
Thanks @matthew-mizielinski for the great work. I checked #85 and couldn't see anything deviating from the discussion here. But it would be good if @jprb-walton also had a look, 4 eyes see more than 2.

**Comment by matthew-mizielinski** [comment]
> Thanks @matthew-mizielinski ! I've checked #85 as well, the only thing I could find is in line 348: `branching off from esm-up2p0-swl4p0-50y-dn2p0`, but should be `branching off from esm-up2p0-gwl4p0-50y-dn2p0` for consistency with the rest of experiment descriptions.

good catch -- corrected in [9fc1048](https://github.com/WCRP-CMIP/CMIP6Plus_CVs/commit/9fc10483c8715222167c6115e04465702b39237f)

**Comment by klauswyser** [comment]
How shall we do with tier 2 experiments? In the OptimESM project there already are other experiments than those listed in #85 (e.g. GWL3) that also wait for cmorisation. The TIPMIP description paper will list these experiments as tier 2.

Shall we add these experiments in #85, or would it be better to first execute !85 and then open a new pull request for tier 2 experiments?

**Comment by klauswyser** [comment]
Here are the Tier 2 experiments for TIPMIP, a couple of additional GWL simulations that we are running as part of OptimESM and/or TipESM. @jprb-walton, do you think these are all extra runs, or do you have any other experiments?

| experiment id | activity id | experiment | tier | sub experiment id | parent experiment id | required model components | additional allowed model components | start year | end year | min number of years | parent activity id | description
|-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
| esm-up2p0-gwl1p5 | TIPMIP | zero CO2 emissions simulation starting at global warming level of 1.5K, branching off from esm-up2p0 | 2 | none | esm-up2p0 | AOGCM BGC | AER CHEM |   |   | 300 | TIPMIP | stabilisation at GWL1.5  
| esm-up2p0-gwl3p0 | TIPMIP | zero CO2 emissions simulation starting at global warming level of 3K, branching off from esm-up2p0 | 2 | none | esm-up2p0 | AOGCM BGC | AER CHEM |   |   | 300 | TIPMIP | stabilisation at GWL3
| esm-up2p0-gwl5p0 | TIPMIP | zero CO2 emissions simulation starting at global warming level of 5K, branching off from esm-up2p0 | 2 | none | esm-up2p0 | AOGCM BGC | AER CHEM |   |   | 300 | TIPMIP | stabilisation at GWL5

Colin confirms that we can add these extra GWL exps in the protocol paper:
>Yes, I think we are within our rights to class
>1.	Zero emission runs at GWL=0K (PI), 2K and 4K as TIPMIP Stream/Tier 1.
>2.	Zero emission runs at GWL = 1.5, 3 and 5K as TIPMIP Stream/Tier 2.
>
>Tier 1 will be “required”, Tier 2 will be “encouraged”, but all can be official TIPMIP runs, so valid on the ESGF.
>We can word it this way in the protocol paper
>
  
Repating my practical question: shall we add these Tier-2 experiments to #85, or open a separate PR later? @matthew-mizielinski , what do you think?

**Comment by matthew-mizielinski** [comment]
Hi @klauswyser. @wolfiex has made some updates to the JSON-LD files that ultimately create the experiment_id.json file which account for the Tier 1 nodes. Could you open a separate issue for the Tier-2 and we'll pick them up independently.

**Comment by klauswyser** [comment]
> Hi @klauswyser. @wolfiex has made some updates to the JSON-LD files that ultimately create the experiment_id.json file which account for the Tier 1 nodes. Could you open a separate issue for the Tier-2 and we'll pick them up independently.

Done, opened #87.

**Comment by matthew-mizielinski** [comment]
Updates in v6.5.2.0 release
